---
title: "Iteration"
author: "Chhiring Lama"
date: "2024-11-13"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(dplyr)
set.seed(1)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "85%", 
	fig.align = "center"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Problem 1

Creating function to see if atleast 2 people share the same birthday:
```{r}
sim_bday <- function(sample_size) {
  
  bdays = sample(1:365, size =sample_size, replace = TRUE)
  
  duplicate <- length(unique(bdays)) < sample_size
  
  return(duplicate)
}
```

Iterations with different sample size
```{r}
sim_results <- expand.grid(
  n = 2:50,
  iter = 1:10000
) |> 
  mutate(estimated_res = map_lgl(n, sim_bday)) |> 
  group_by(n) |> 
  summarize(prop = mean(estimated_res))
```

Plotting the probability
```{r, fig.width = 5,fig.height = 4, out.width = "60%",}
sim_results |> 
  ggplot(aes(x = n, y = prop)) +
  geom_point() +
  labs(x = "Group Size", y = "Probability",
       title = "Probability of at least two people with same birthday")
```

